name: cms
description: A new Nowa project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  nowa_runtime: ^0.1.2
  flutter_html: ^3.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  collection: ^1.19.1
  intl: 0.20.2
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/AppIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/appIcon.png
